server:
  applicationConnectors:
    - type: http
      port: ${APP_PORT:-8080}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8081}

jwtConfig:
  secret: ${JWT_SECRET:-toomanysecrets}
  tokenTimeToLive: ${JWT_TTL:-60 minute}

dataSource:
  #driverClass: ${DB_DRIVER:-org.hsqldb.jdbc.JDBCDriver}
  driverClass: ${DB_DRIVER:-org.h2.Driver}
  #url: ${DB_URL:-jdbc:hsqldb:mem:myDb}
  url: ${DB_URL:-jdbc:h2:mem:test}
  #url: ${DB_URL:-jdbc:h2:./test}
  user: ${DB_USERNAME:-sa}
  password: ${DB_PWD:-sa}
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "CALL NOW()"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

logging:
  appenders:
    - type: console
      threshold: DEBUG
      logFormat: "%-5p [%d{ISO8601,UTC}] [authUser=%X{userId}] [%thread] %logger{0}: %m%n%rEx"

