#%RAML 1.0
title: CRM Service API
baseUri: http://localhost:8080
version: 1.0
mediaType: application/json
traits:
  unauthorized-error: !include unauthorized-error.raml
  invalid-request-error: !include invalid-error.raml
  not-found-error: !include not-found-error.raml
  stale-entity-error: !include stale-entity-error.raml
  authorized:
    description: Request authorization mechanism
    headers:
      x-auth-token:
        required: true

/crm/users:
    displayName: Collection resource for the User entity
    is: [authorized, unauthorized-error]
    get:
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                            "items": [
                                {
                                    "id": "fd383951-ff29-4eb2-ad64-9d1b22270d7e",
                                    "name": "John Smith",
                                    "username": "jsmith",
                                    "role": "admin"
                                },
                                {...}
                            ]}
    post:
        is: [invalid-request-error]
        body:
            application/json:
                 example: |
                    {
                        "name": "John Smith",
                        "username": "jsmith",
                        "password": "some-password",
                        "role": "admin"
                    }
        responses:
            201:
                body:
                    application/json:
                        example: |
                            {
                                "id": "fd383951-ff29-4eb2-ad64-9d1b22270d7e",
                            }
    /{userId}:
        displayName: Resource for individual User operations
        is: [authorized, unauthorized-error, invalid-request-error, not-found-error]
        get:
            responses:
                200:
                    headers:
                        ETag:
                            description: The user version number for optimistic locking on update
                    body:
                        example: |
                            {
                                "id": "fd383951-ff29-4eb2-ad64-9d1b22270d7e",
                                "name": "John Smith",
                                "username": "jsmith",
                                "role": "user"
                            }
        put:
            headers:
                If-Match:
                    description: The user version number returned in the GET call.
            body:
                example | 
                    {
                        "name": "John Smith",
                        "username": "jsmith",
                        "password": "some-password",
                        "role": "admin"
                    }
            responses:
                204:
        patch:
            headers:
                If-Match:
                    description: The user version number returned in the GET call.
            body:
                example | 
                    {
                        "role": "admin"
                    }
            responses:
                204:
        delete:
            responses:
                204: