#%RAML 1.0
title: CRM Customer API
baseUri: http://localhost:8080
version: 1.0
mediaType: application/json
traits:
  unauthorized-error: !include unauthorized-error.raml
  invalid-request-error: !include invalid-error.raml
  duplicated-error: !include duplicated-error.raml
  not-found-error: !include not-found-error.raml
  stale-entity-error: !include stale-entity-error.raml
  authorized:
    description: Request authorization mechanism
    headers:
      Authorization:
        required: true

/crm/customers:
    description: Collection resource for the Customer entity
    is: [authorized, unauthorized-error]
    get:
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                            "items": [
                                {
                                    "customerId": "fd383951-ff29-4eb2-ad64-9d1b22270d7e",
                                    "id": "provided-id",
                                    "name": "John",
                                    "surname": "Smith",
                                    "photoUrl": "http://localhost:8080/crm/customers/fd383951-ff29-4eb2-ad64-9d1b22270d7e/image",
                                    "createdBy": "fd383951-ff29-4eb2-ad64-9d1b22270d7e",
                                    "updatedBy": "fd383951-ff29-4eb2-ad64-9d1b22270d7e"
                                },
                                {...}
                            ]}
    post:
        is: [invalid-request-error, duplicated-error]
        body:
            application/json:
                 example: |
                    {
                        "id": "providedId",
                        "name": "John",
                        "surname": "Smith"
                    }
        responses:
            201:
                headers:
                    ETag:
                       description: The user version number for optimistic locking on update
                    Location:
                       description: The URL tp get the customer
                body:
                    application/json:
                        example: |
                            {
                                "customerId": "fd383951-ff29-4eb2-ad64-9d1b22270d7e",
                            }
    /{customerId}:
        description: Resource for individual Customer operations
        is: [authorized, unauthorized-error, invalid-request-error, not-found-error]
        get:
            responses:
                200:
                    headers:
                        ETag:
                            description: The user version number for optimistic locking on update
                    body:
                        application/json:
                            example: |
                                {
                                    "customerId": "fd383951-ff29-4eb2-ad64-9d1b22270d7e",
                                    "id": "provided-id",
                                    "name": "John",
                                    "surname": "Smith",
                                    "photoUrl": "http://localhost:8080/crm/customers/fd383951-ff29-4eb2-ad64-9d1b22270d7e/image",
                                    "createdBy": "fd383951-ff29-4eb2-ad64-9d1b22270d7e",
                                    "updatedBy": "fd383951-ff29-4eb2-ad64-9d1b22270d7e"
                                }
        put:
            is: [stale-entity-error, duplicated-error]
            headers:
                If-Match:
                    description: The user version number returned in the GET call.
            body:
                application/json:
                    example: |
                        {
                            "id": "providedId",
                            "name": "John",
                            "surname": "Smith"
                        }
            responses:
                204:
        delete:
            responses:
                204: