responses:
    403:
        description: Authenticated user does not have access to the resource
        body:
            application/json:
                example: {"code": 403, "message": "User not authorized."}